package com.example.activediet.services

import android.annotation.SuppressLint
import android.app.NotificationChannel
import android.app.NotificationManager
import android.app.PendingIntent
import android.content.Context
import android.content.Intent
import android.location.Location
import android.os.Build
import android.os.Looper
import androidx.annotation.RequiresApi
import androidx.core.app.NotificationCompat
import androidx.lifecycle.LifecycleService
import androidx.lifecycle.MutableLiveData
import androidx.lifecycle.Observer
import com.example.activediet.R
import com.example.activediet.utilities.run.Constants.ACTION_PAUSE_SERVICE
import com.example.activediet.utilities.run.Constants.ACTION_START_OR_RESUME_SERVICE
import com.example.activediet.utilities.run.Constants.ACTION_STOP_SERVICE
import com.example.activediet.utilities.run.Constants.FASTEST_LOCATION_INTERVAL
import com.example.activediet.utilities.run.Constants.LOCATION_UPDATE_INTERVAL
import com.example.activediet.utilities.run.Constants.NOTIFICATION_CHANNEL_ID
import com.example.activediet.utilities.run.Constants.NOTIFICATION_CHANNEL_NAME
import com.example.activediet.utilities.run.Constants.NOTIFICATION_ID
import com.example.activediet.utilities.run.Constants.TIMER_UPDATE_INTERVAL
import com.example.activediet.utilities.run.TrackingUtility
import com.google.android.gms.location.FusedLocationProviderClient
import com.google.android.gms.location.LocationCallback
import com.google.android.gms.location.LocationRequest
import com.google.android.gms.location.LocationResult
import com.google.android.gms.maps.model.LatLng
import dagger.hilt.android.AndroidEntryPoint
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import timber.log.Timber
import javax.inject.Inject

